language: elixir
elixir:
- 1.6.0
otp_release:
- 20.2.2
before_deploy:
  - rm -rf ~/.nvm && curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash && nvm install node && nvm use node
  - cd priv/contact-react && yarn install && yarn build && cd - 
deploy:
  provider: heroku
  api_key:
    secure: Y6o2Ql/Dk/o4R/uQ+xYMKtwMd7UT12j05vCSS449W7vMYL8it3C/tznwJI3f7UCdkstloPzVhHHW35yc8TJhSl33JF5hfEyuYStlmq/Ud+o4kxT8/e9agG1ndktuI6D29Xz0Me3PHFT3ZFR3WcYdIW0MHJgWaafgidweBaSdWEcJS9nxkNCnsAX+TTDYmjurqs1maCkxeJTue6EcijXiuil1e8dZvnWoiMxz0KRNxXJUSflS5BBqQtAe8A3bKq9dw/p/JdyqwVMY7iEXlpqWTAslO1ahnBQKT9OBa5fwF49+xNNXTKIn9GIMElF/ivRCa2yYWw7Kh7gAbdk4ntxvPB7j9XKwHtoaV1xktSpua8ZtpzJzVOdHRSph391zsIMKo3JgbtpyiJzqUntXzyiMwxhzPu4DVIwut6cd+aOWb5ZdYI64XIgskERkXzNf1MhzTKbI5UEeoXTo7PM1xCned3caGyqwOWWElAkh3vAFq6Rz7C6A+tsL8aahf48aRg9zDd0o5JH6xK2UNppTiXE6Qs9MleH/qSvedubJuxvq6r0lzuOmYBF1jyIGDfan/zURjWKUZpSLRTfCLR2g1Uj5ObcqqzRkXJp1hGvA8c0IZUf9Ynt4vbxHkfVAyZMo1Z2NOjyiAhw2iTAeNMAxfS7iSDM75H5PeqcmIziQN/RPIkI=
  skip_cleanup: true
  app: quiet-atoll-83762
  on:
    repo: mhanberg/contact
  run:
    - "mix ecto.migrate"
